ALTER TABLE area
DROP CONSTRAINT area_name_key;

--ALTER TABLE area
--ALTER COLUMN name DROP UNIQUE(name);
--ALTER TABLE hotel
--ALTER COLUMN name DROP CONSTRAINT UNIQUE;
--ALTER TABLE customer
--ALTER COLUMN name DROP CONSTRAINT UNIQUE;
